title: The Importance of Deep Sleep
author: Just another GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Things that go on during deep sleep that you'll never be able 
  to check for yourself...

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
